package com.juvarya.user.access.mgmt.dto.enums;

public enum PermissionType {
    CAN_CREATE_OR_UPDATE_TABLE,
    CAN_ADD_PRODUCT,
    CAN_REMOVE_PRODUCT,
    CAN_UPDATE_PRODUCT_QTY,
    CAN_VIEW_ORDER_DETAILS,
    CAN_COMPLETE_ORDER,
    CAN_GET_ORDER_BY_ID,
    CAN_CANCEL_ORDER,
    CAN_VIEW_ALL_ORDERS,
    CAN_VIEW_ORDERS_BY_STATUS

}
