-- Roles
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50)
);

-- Users
CREATE TABLE IF NOT EXISTS B2B_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(150) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(50),
    EMAIL_HASH VARCHAR(255) UNIQUE,
    PRIMARY_CONTACT VARCHAR(50),
    PRIMARY_CONTACT_HASH VARCHAR(255) UNIQUE,
    GENDER VARCHAR(10),
    PROFILE_PICTURE_ID BIGINT,
    FCM_TOKEN VARCHAR(255),
    JUVI_ID VARCHAR(50),
    PASSWORD VARCHAR(255),
    RECENT_ACTIVITY_DATE DATE,
    LAST_LOGOUT_DATE DATE,
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESET_TOKEN VARCHAR(255),
    RESET_TOKEN_EXPIRY TIMESTAMP
);

-- User Roles
CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES B2B_USER(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES roles(ID)
);

-- Address
CREATE TABLE IF NOT EXISTS user_address (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    street VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    postal_code VARCHAR(20),
    latitude DECIMAL(10,6),
    longitude DECIMAL(10,6),
    is_default BOOLEAN,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES B2B_USER(ID)
);

-- Business Category
CREATE TABLE IF NOT EXISTS business_categories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(500)
);

-- B2B Unit
CREATE TABLE IF NOT EXISTS B2B_UNIT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    OWNER_USER_ID BIGINT NOT NULL,
    BUSINESS_NAME VARCHAR(150) NOT NULL,
    CATEGORY_ID BIGINT,
    CONTACT_NUMBER VARCHAR(20),
    BUSINESS_LATITUDE DECIMAL(10,6),
    BUSINESS_LONGITUDE DECIMAL(10,6),
    ENABLED BOOLEAN DEFAULT TRUE,
    ADDRESS_ID BIGINT NOT NULL,
    IS_TEMPORARILY_CLOSED BOOLEAN DEFAULT FALSE,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OWNER_USER_ID) REFERENCES B2B_USER(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES business_categories(ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES user_address(ID)
);

-- Business Attributes
CREATE TABLE IF NOT EXISTS business_attribute (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    attribute_name VARCHAR(255),
    attribute_value VARCHAR(255),
    b2b_unit_id BIGINT,
    FOREIGN KEY (b2b_unit_id) REFERENCES B2B_UNIT(ID)
);

-- User Attributes
CREATE TABLE IF NOT EXISTS user_attribute (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    attribute_name VARCHAR(100),
    attribute_value VARCHAR(500),
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES B2B_USER(ID)
);

-- Media
CREATE TABLE IF NOT EXISTS media (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    business_id BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    file_name VARCHAR(255),
    media_type VARCHAR(50),
    description VARCHAR(500),
    extension VARCHAR(10),
    active BOOLEAN DEFAULT TRUE,
    customer_id BIGINT,
    created_by BIGINT,
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modification_time TIMESTAMP,
    name VARCHAR(255),
    FOREIGN KEY (business_id) REFERENCES B2B_UNIT(ID)
);

-- User Business Role Mapping
CREATE TABLE IF NOT EXISTS user_business_role_mappings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    b2b_unit_id BIGINT,
    role VARCHAR(50) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (user_id) REFERENCES B2B_USER(ID),
    FOREIGN KEY (b2b_unit_id) REFERENCES B2B_UNIT(ID)
);

-- User OTP
CREATE TABLE IF NOT EXISTS USER_OTP (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    OTP_TYPE VARCHAR(50),
    CHANNEL VARCHAR(50),
    EMAIL_ADDRESS VARCHAR(50),
    user_model_id BIGINT,
    CREATION_TIME TIMESTAMP,
    OTP VARCHAR(10),
    PRIMARY_CONTACT VARCHAR(20),
    FOREIGN KEY (user_model_id) REFERENCES B2B_USER(ID)
);
